# Spring Mail 配置
spring:
  # 邮件服务器SMTP主机地址
  mail:
    host: smtp.qq.com
    # 发送邮件的邮箱用户名
    username: xxx@xxx.com
    # 发送邮件的邮箱密码或授权码
    password: xxx
    # 高级属性配置，用于定制邮件发送的行为和连接设置
    properties:
      # 指定SSL套接字工厂类，用于安全连接
      "[mail.smtp.socketFactory.class]": javax.net.ssl.SSLSocketFactory
      # 如果创建SSL套接字失败，是否允许降级到非SSL连接，默认为false表示不允许降级
      "[mail.smtp.socketFactory.fallback]": false
      # SSL套接字连接的端口号，默认为465，这是SMTPS（SMTP over SSL）的标准端口
      "[mail.smtp.socketFactory.port]": 465
      # 连接到SMTP服务器的超时时间（以毫秒为单位），默认为5000毫秒
      "[mail.smtp.connectiontimeout]": 5000
      # 等待服务器响应的超时时间（以毫秒为单位），默认为3000毫秒
      "[mail.smtp.timeout]": 3000
      # 写数据到SMTP服务器的超时时间（以毫秒为单位），默认为5000毫秒
      "[mail.smtp.writetimeout]": 5000

# 自定义邮件发送配置
mail:
  # 发送邮件时默认的发件人邮箱地址
  from: xxx@xxx.com
  # 发件人的个性化名称，显示在邮件客户端的“发件人”栏
  personal: JAVGO
  # 隐秘抄送地址，收件人不会看到此列表中的其他收件人
  bcc: xxx@xxx.com
  # 预设邮件主题，方便快速发送测试或特定主题邮件
  subject: JAVGO 测试邮件

javgo:
  starter:
    enabled: true

debug: true